### ISSUE TITLE
Syntax error when styling field / card buttons

### ISSUE THREAD

**Issue by brownbat** [AnKing-VIP/The-KING-of-Button-Add-ons#10]
Adding the styling to the "field" and "card" buttons causes a syntax error. (Might be why that section is commented out!)

```---------------------------
Anki
---------------------------
An add-on you installed failed to load. If problems persist, please go to the Tools>Add-ons menu, and disable or delete the add-on.

When loading '⁨KING⁩':
⁨Traceback (most recent call last):
  File "aqt\addons.py", line 211, in loadAddons
  File "C:\Users\----\AppData\Roaming\Anki2\addons21\KING\__init__.py", line 10, in <module>
    from . import bottom_main_buttons
  File "C:\Users\----\AppData\Roaming\Anki2\addons21\KING\bottom_main_buttons.py", line 64
    aqt.editor._html +=
                      ^
SyntaxError: invalid syntax
⁩
---------------------------
OK   
---------------------------```

Great add on, this issue is probably premature and not urgent, but wanted to just give you a heads up.

**Comment by AnKingMed** [comment]
I'm not sure what you mean with this. What are you trying to do?

**Comment by brownbat** [comment]
I just read this in the code:

```## If you want to style the "field" and "card" buttons in the editor, 
## delete the ''' at the beginning and end of this section```

If you actually do that, though, it creates a syntax error.

You probably can fix that by moving the ```(""" ``` on line 65 up to line 64.

**Comment by abdnh** [comment]
Even without the syntax error, the code is outdated and no longer works, so I removed it.
