### ISSUE TITLE
23.10 defaults error - can't push tooltip

### ISSUE THREAD

**Issue by working-name** [AnKing-VIP/The-KING-of-Button-Add-ons#30]
```python
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue to the add-on author.
Debug info:
Anki 23.10 (51a10f09) Python 3.9.15 Qt 6.5.3 PyQt 6.5.3
Platform: macOS-13.5.2-arm64-arm-64bit
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2023-11-03 23:04:47
Add-ons possibly involved: ⁨The KING of Button Add-ons⁩

Caught exception:
Traceback (most recent call last):
  File "aqt.webview", line 608, in handler
  File "aqt.reviewer", line 541, in _onAnswerButton
  File "decorator", line 232, in fun
  File "anki.hooks", line 89, in decorator_wrapper
  File "anki.hooks", line 83, in repl
  File "/Users/user/Library/Application Support/Anki2/addons21/374005964/confirmation.py", line 118, in answerCard_before
    custom_tooltip_helper("Good", GoodColor, x3)
  File "/Users/user/Library/Application Support/Anki2/addons21/374005964/confirmation.py", line 101, in custom_tooltip_helper
    utils.tooltipWithColour("<div style='color:#3a3a3a;%s'>%s</div>" % (FONTSIZE, label),
  File "/Users/user/Library/Application Support/Anki2/addons21/374005964/custom_tooltip.py", line 38, in tooltipWithColour
    lab.setFrameStyle(QFrame.Panel)
AttributeError: type object 'QFrame' has no attribute 'Panel'

```

config:

```json
{
    "AgainColor": "red",
    "EasyColor": "#61a8ff",
    "GoodColor": "#30c257",
    "HardColor": "orange",
    "Nightmode_AgainColor": "#ff6961",
    "Nightmode_EasyColor": "#61a8ff",
    "Nightmode_GoodColor": "#61ffb8",
    "Nightmode_HardColor": "#ffb861",
    "answer button width": "Full",
    "border radius": "3",
    "button color": "hover",
    "button font size": "S",
    "button height": "S",
    "button width": "S",
    "confirmation": true,
    "confirmation time": 450,
    "confirmation x-offset": 0,
    "confirmation y-offset": 0,
    "outline": "yes",
    "style main screen buttons": true
}
```

also your config panel has broken iimages - maybe store locally in plugin files and find another way to track usage?

**Comment by AnKingMed** [comment]
@abdnh @DoctorToBeIn23 looks like we may need to look into this one

**Comment by AnKingMed** [comment]
Oh nice. You can go ahead and push it to ankiweb

**Comment by abdnh** [comment]
Done.
